name: Deploy to AWS EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install Dependencies
        run: npm install

      - name: Build Application
        run: npm run build

      - name: Build Docker Image
        run: docker build -t quicknote:01 .

      - name: Save Docker Image to Tar
        run: docker save quicknote:01 > quicknote01.tar

      - name: Copy Docker Image to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "quicknote01.tar"
          target: "/home/ec2-user/"

      - name: Deploy on EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker load < quicknote01.tar
            docker stop quicknote || true
            docker rm quicknote || true
            docker run -d --name quicknote -p 3000:3000 quicknote
